name: CD

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: [3.6, 3.7]
        include:
          - { os: ubuntu-latest, python-version: 3.6, python-abis: "cp36-cp36m" }
          - { os: ubuntu-latest, python-version: 3.7, python-abis: "cp37-cp37m" }
          - { os: windows-latest, python-version: 3.7, build-static: 1 }

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up conda ${{ matrix.python-version }}
        env:
          PYTHON: ${{ matrix.python-version }}
        shell: bash
        run: |
          source ./.github/workflows/install-conda.sh
          if [[ `uname` == "Darwin" ]]; then
            brew reinstall gcc@10
          fi

      - name: Deploy packages
        if: startsWith(github.ref, 'refs/tags/') && matrix.no-deploy != '1'
        shell: bash
        env:
          DOCKER_IMAGE: "quay.io/pypa/manylinux1_x86_64"
          PYABI: ${{ matrix.python-abis }}
          BUILD_STATIC: ${{ matrix.build-static }}
          PYPI_PWD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          source ./.github/workflows/reload-env.sh
          source ./.github/workflows/upload-packages.sh
